language: python
python:
  - 2.7
script:
  - make test-sqlite
  - make test-flake8
notifications:
  email:
  - ci-notify@openlabs.co.in
env:
  - LINKEDIN_API_KEY=dwgzv26amdf3 LINKEDIN_API_SECRET=CegPGgH2sEnC2fz7
